In [44]:
import pandas as pd
import numpy as np
data=pd.read_csv("titanic.csv")
data=data.set_index('Unnamed: 0')
data.index.name='sno'
data.tail(20)



Name PClass   Age     Sex  Survived  SexCode
sno                                                                   
1294         Wilkes, Mrs Ellen    3rd  45.0  female         1        1
1295          Willer, Mr Aaron    3rd   NaN    male         0        0
1296         Willey, Mr Edward    3rd   NaN    male         0        0
1297  Williams, Mr Howard Hugh    3rd   NaN    male         0        0
1298       Williams, Mr Leslie    3rd  28.0    male         0        0
1299        Windelov, Mr Einar    3rd  21.0    male         0        0
1300           Wirz, Mr Albert    3rd  27.0    male         0        0
1301     Wiseman, Mr Phillippe    3rd   NaN    male         0        0
1302   Wittevrongel, Mr Camiel    3rd  36.0    male         0        0
1303         Yalsevac, Mr Ivan    3rd   NaN    male         1        0
1304        Yasbeck, Mr Antoni    3rd  27.0    male         0        0
1305       Yasbeck, Mrs Antoni    3rd  15.0  female         1        1
1306        Youssef, Mr Gerios    3rd   NaN    male         0        0
1307       Zabour, Miss Hileni    3rd   NaN  female         0        1
1308       Zabour, Miss Tamini    3rd   NaN  female         0        1
1309        Zakarian, Mr Artun    3rd  27.0    male         0        0
1310    Zakarian, Mr Maprieder    3rd  26.0    male         0        0
1311          Zenni, Mr Philip    3rd  22.0    male         0        0
1312          Lievens, Mr Rene    3rd  24.0    male         0        0
1313            Zimmerman, Leo    3rd  29.0    male         0        0

In [45]:
data.Sex.Value_counts

AttributeError: 'Series' object has no attribute 'Value_counts'

In [46]:

li=range(45,70)
li=list(li)  # series using list
li.append('a')
s1=pd.Series(li)
type(s1)

pandas.core.series.Series

In [47]:
s1[0:2]

0    45
1    46
dtype: object

In [48]:
type(s1)
s1

0     45
1     46
2     47
3     48
4     49
5     50
6     51
7     52
8     53
9     54
10    55
11    56
12    57
13    58
14    59
15    60
16    61
17    62
18    63
19    64
20    65
21    66
22    67
23    68
24    69
25     a
dtype: object

In [49]:

n=np.array([1,2,3])  # series using array
s2=pd.Series(n)
s2

0    1
1    2
2    3
dtype: int64

In [50]:
type(s2.index)

pandas.indexes.range.RangeIndex

In [51]:
d={'a':1,'b':2,'c':3} #series using dictionary
li=list(range(3))
s2=pd.Series(d,index=['b','a','c'],name='pb')
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [52]:
type(s2.values)

numpy.ndarray

In [53]:
s2.values


array([2, 1, 3])

In [54]:
s2**3**2

b      512
a        1
c    19683
Name: pb, dtype: int64

In [55]:
a=s2**9
print(a)
b=a**2
print(b)

b      512
a        1
c    19683
Name: pb, dtype: int64
b       262144
a            1
c    387420489
Name: pb, dtype: int64


In [56]:
np.log(s2)

b    0.693147
a    0.000000
c    1.098612
Name: pb, dtype: float64

In [57]:
s2['b':'a']

b    2
a    1
Name: pb, dtype: int64

In [58]:
s2[0:2]

b    2
a    1
Name: pb, dtype: int64

In [59]:
c=pd.Series({'d':22})
s=s2.add(c)
s

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [60]:
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [61]:
for i,v in enumerate(s2):
    print(i,"--",v)

0 -- 2
1 -- 1
2 -- 3


In [62]:
li=[x*2 for x in s2]
li

[4, 2, 6]

In [63]:
'c' in s2

True

In [64]:
for k,v in s2.iteritems():
    print(k,v)

b 2
a 1
c 3


In [65]:
li=np.random.rand(5,2,3)
li

array([[[ 0.88091972,  0.15847747,  0.58701996],
        [ 0.59405407,  0.88371706,  0.19499825]],

       [[ 0.10400354,  0.57453182,  0.66133424],
        [ 0.29907295,  0.32244447,  0.82704111]],

       [[ 0.76331955,  0.09964797,  0.84512439],
        [ 0.94529174,  0.43330395,  0.12876011]],

       [[ 0.8930249 ,  0.74350829,  0.99341446],
        [ 0.98959231,  0.93487474,  0.26762781]],

       [[ 0.97487557,  0.70811565,  0.34045428],
        [ 0.32036795,  0.65794757,  0.40065557]]])

In [66]:
li

array([[[ 0.88091972,  0.15847747,  0.58701996],
        [ 0.59405407,  0.88371706,  0.19499825]],

       [[ 0.10400354,  0.57453182,  0.66133424],
        [ 0.29907295,  0.32244447,  0.82704111]],

       [[ 0.76331955,  0.09964797,  0.84512439],
        [ 0.94529174,  0.43330395,  0.12876011]],

       [[ 0.8930249 ,  0.74350829,  0.99341446],
        [ 0.98959231,  0.93487474,  0.26762781]],

       [[ 0.97487557,  0.70811565,  0.34045428],
        [ 0.32036795,  0.65794757,  0.40065557]]])