In [16]:
import pandas as pd
import numpy as np
data=pd.read_csv("titanic.csv")
#data=data.set_index('Unnamed: 0')
data.index.name='sno'
data.head(20)



PassengerId  Survived  Pclass  \
sno                                  
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   

                                                  Name     Sex   Age  SibSp  \
sno                                                                           
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN      0   

     Parch            Ticket     Fare Cabin Embarked  
sno                                                   
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
5        0            330877   8.4583   NaN        Q  
6        0             17463  51.8625   E46        S  
7        1            349909  21.0750   NaN        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
10       1           PP 9549  16.7000    G6        S  
11       0            113783  26.5500  C103        S  
12       0         A/5. 2151   8.0500   NaN        S  
13       5            347082  31.2750   NaN        S  
14       0            350406   7.8542   NaN        S  
15       0            248706  16.0000   NaN        S  
16       1            382652  29.1250   NaN        Q  
17       0            244373  13.0000   NaN        S  
18       0            345763  18.0000   NaN        S  
19       0              2649   7.2250   NaN        C

In [3]:
k=data.Sex.value_counts()
k

male      577
female    314
Name: Sex, dtype: int64

In [4]:

li=range(45,70)
li=list(li)  # series using list
li.append('a')
s1=pd.Series(li)
type(s1)

pandas.core.series.Series

In [5]:
s1[0:2]

0    45
1    46
dtype: object

In [6]:
type(s1)
s1

0     45
1     46
2     47
3     48
4     49
5     50
6     51
7     52
8     53
9     54
10    55
11    56
12    57
13    58
14    59
15    60
16    61
17    62
18    63
19    64
20    65
21    66
22    67
23    68
24    69
25     a
dtype: object

In [7]:

n=np.array([1,2,3])  # series using array
s2=pd.Series(n)
s2

0    1
1    2
2    3
dtype: int64

In [8]:
type(s2.index)

pandas.core.indexes.range.RangeIndex

In [9]:
d={'a':1,'b':2,'c':3} #series using dictionary
li=list(range(3))
s2=pd.Series(d,index=['b','a','c'],name='pb')
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [10]:
type(s2.values)

numpy.ndarray

In [11]:
s2.values


array([2, 1, 3])

In [12]:
s2**3**2

b      512
a        1
c    19683
Name: pb, dtype: int64

In [13]:
a=s2**9
print(a)
b=a**2
print(b)

b      512
a        1
c    19683
Name: pb, dtype: int64
b       262144
a            1
c    387420489
Name: pb, dtype: int64


In [14]:
np.log(s2)

b    0.693147
a    0.000000
c    1.098612
Name: pb, dtype: float64

In [15]:
s2['b':'a']

b    2
a    1
Name: pb, dtype: int64

In [15]:
s2[0:2]

b    2
a    1
Name: pb, dtype: int64

In [16]:
c=pd.Series({'d':22})
s=s2.add(c)
s

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [17]:
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [18]:
for i,v in enumerate(s2):
    print(i,"--",v)

0 -- 2
1 -- 1
2 -- 3


In [19]:
li=[x*2 for x in s2]
li

[4, 2, 6]

In [20]:
'c' in s2

True

In [21]:
for k,v in s2.iteritems():
    print(k,v)

b 2
a 1
c 3


In [22]:
li=np.random.rand(5,2,3)
li

array([[[ 0.79296046,  0.17107875,  0.45100389],
        [ 0.1244159 ,  0.31380031,  0.43099861]],

       [[ 0.4240695 ,  0.01987727,  0.59924167],
        [ 0.52340634,  0.92714485,  0.40366242]],

       [[ 0.68912748,  0.52897909,  0.04415841],
        [ 0.09158876,  0.52364913,  0.52685807]],

       [[ 0.17552677,  0.2384511 ,  0.30583214],
        [ 0.86265952,  0.84974727,  0.4796934 ]],

       [[ 0.15986668,  0.93220515,  0.01656867],
        [ 0.68920142,  0.22443914,  0.59614782]]])

In [23]:
li

array([[[ 0.79296046,  0.17107875,  0.45100389],
        [ 0.1244159 ,  0.31380031,  0.43099861]],

       [[ 0.4240695 ,  0.01987727,  0.59924167],
        [ 0.52340634,  0.92714485,  0.40366242]],

       [[ 0.68912748,  0.52897909,  0.04415841],
        [ 0.09158876,  0.52364913,  0.52685807]],

       [[ 0.17552677,  0.2384511 ,  0.30583214],
        [ 0.86265952,  0.84974727,  0.4796934 ]],

       [[ 0.15986668,  0.93220515,  0.01656867],
        [ 0.68920142,  0.22443914,  0.59614782]]])

In [24]:
di={'name':['prince','bharti','rahul','tiwari'],'s.no':[22,45,23,655]}


In [25]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S