In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv("titanic.csv")
data=data.set_index('Unnamed: 0')
data.index.name='sno'
data.head(20)



KeyError: 'Unnamed: 0'

In [2]:
k=data.Sex.value_counts()
k

male      577
female    314
Name: Sex, dtype: int64

In [3]:

li=range(45,70)
li=list(li)  # series using list
li.append('a')
s1=pd.Series(li)
type(s1)

pandas.core.series.Series

In [4]:
s1[0:2]

0    45
1    46
dtype: object

In [5]:
type(s1)
s1

0     45
1     46
2     47
3     48
4     49
5     50
6     51
7     52
8     53
9     54
10    55
11    56
12    57
13    58
14    59
15    60
16    61
17    62
18    63
19    64
20    65
21    66
22    67
23    68
24    69
25     a
dtype: object

In [6]:

n=np.array([1,2,3])  # series using array
s2=pd.Series(n)
s2

0    1
1    2
2    3
dtype: int64

In [7]:
type(s2.index)

pandas.core.indexes.range.RangeIndex

In [8]:
d={'a':1,'b':2,'c':3} #series using dictionary
li=list(range(3))
s2=pd.Series(d,index=['b','a','c'],name='pb')
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [9]:
type(s2.values)

numpy.ndarray

In [10]:
s2.values


array([2, 1, 3])

In [11]:
s2**3**2

b      512
a        1
c    19683
Name: pb, dtype: int64

In [12]:
a=s2**9
print(a)
b=a**2
print(b)

b      512
a        1
c    19683
Name: pb, dtype: int64
b       262144
a            1
c    387420489
Name: pb, dtype: int64


In [13]:
np.log(s2)

b    0.693147
a    0.000000
c    1.098612
Name: pb, dtype: float64

In [14]:
s2['b':'a']

b    2
a    1
Name: pb, dtype: int64

In [15]:
s2[0:2]

b    2
a    1
Name: pb, dtype: int64

In [16]:
c=pd.Series({'d':22})
s=s2.add(c)
s

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [17]:
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [18]:
for i,v in enumerate(s2):
    print(i,"--",v)

0 -- 2
1 -- 1
2 -- 3


In [19]:
li=[x*2 for x in s2]
li

[4, 2, 6]

In [20]:
'c' in s2

True

In [21]:
for k,v in s2.iteritems():
    print(k,v)

b 2
a 1
c 3


In [22]:
li=np.random.rand(5,2,3)
li

array([[[ 0.79296046,  0.17107875,  0.45100389],
        [ 0.1244159 ,  0.31380031,  0.43099861]],

       [[ 0.4240695 ,  0.01987727,  0.59924167],
        [ 0.52340634,  0.92714485,  0.40366242]],

       [[ 0.68912748,  0.52897909,  0.04415841],
        [ 0.09158876,  0.52364913,  0.52685807]],

       [[ 0.17552677,  0.2384511 ,  0.30583214],
        [ 0.86265952,  0.84974727,  0.4796934 ]],

       [[ 0.15986668,  0.93220515,  0.01656867],
        [ 0.68920142,  0.22443914,  0.59614782]]])

In [23]:
li

array([[[ 0.79296046,  0.17107875,  0.45100389],
        [ 0.1244159 ,  0.31380031,  0.43099861]],

       [[ 0.4240695 ,  0.01987727,  0.59924167],
        [ 0.52340634,  0.92714485,  0.40366242]],

       [[ 0.68912748,  0.52897909,  0.04415841],
        [ 0.09158876,  0.52364913,  0.52685807]],

       [[ 0.17552677,  0.2384511 ,  0.30583214],
        [ 0.86265952,  0.84974727,  0.4796934 ]],

       [[ 0.15986668,  0.93220515,  0.01656867],
        [ 0.68920142,  0.22443914,  0.59614782]]])

In [24]:
di={'name':['prince','bharti','rahul','tiwari'],'s.no':[22,45,23,655]}


In [25]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S