In [147]:
import pandas as pd
import numpy as np
data=pd.read_csv("titanic.csv")
data=data.set_index('Unnamed: 0')
data.index.name='sno'
data.head(20)



Name PClass    Age     Sex  \
sno                                                                           
1                        Allen, Miss Elisabeth Walton    1st  29.00  female   
2                         Allison, Miss Helen Loraine    1st   2.00  female   
3                 Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
4       Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
5                       Allison, Master Hudson Trevor    1st   0.92    male   
6                                  Anderson, Mr Harry    1st  47.00    male   
7                    Andrews, Miss Kornelia Theodosia    1st  63.00  female   
8                              Andrews, Mr Thomas, jr    1st  39.00    male   
9        Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female   
10                             Artagaveytia, Mr Ramon    1st  71.00    male   
11                          Astor, Colonel John Jacob    1st  47.00    male   
12   Astor, Mrs John Jacob (Madeleine Talmadge Force)    1st  19.00  female   
13                       Aubert, Mrs Leontine Pauline    1st    NaN  female   
14                           Barkworth, Mr Algernon H    1st    NaN    male   
15                                 Baumann, Mr John D    1st    NaN    male   
16     Baxter, Mrs James (Helene DeLaudeniere Chaput)    1st  50.00  female   
17                            Baxter, Mr Quigg Edmond    1st  24.00    male   
18                                Beattie, Mr Thomson    1st  36.00    male   
19                       Beckwith, Mr Richard Leonard    1st  37.00    male   
20    Beckwith, Mrs Richard Leonard (Sallie Monypeny)    1st  47.00  female   

     Survived  SexCode  
sno                     
1           1        1  
2           0        1  
3           0        0  
4           0        1  
5           1        0  
6           1        0  
7           1        1  
8           0        0  
9           1        1  
10          0        0  
11          0        0  
12          1        1  
13          1        1  
14          1        0  
15          0        0  
16          1        1  
17          0        0  
18          0        0  
19          1        0  
20          1        1

In [148]:
k=data.Sex.value_counts()
k

male      851
female    462
Name: Sex, dtype: int64

In [149]:

li=range(45,70)
li=list(li)  # series using list
li.append('a')
s1=pd.Series(li)
type(s1)

pandas.core.series.Series

In [150]:
s1[0:2]

0    45
1    46
dtype: object

In [151]:
type(s1)
s1

0     45
1     46
2     47
3     48
4     49
5     50
6     51
7     52
8     53
9     54
10    55
11    56
12    57
13    58
14    59
15    60
16    61
17    62
18    63
19    64
20    65
21    66
22    67
23    68
24    69
25     a
dtype: object

In [152]:

n=np.array([1,2,3])  # series using array
s2=pd.Series(n)
s2

0    1
1    2
2    3
dtype: int64

In [153]:
type(s2.index)

pandas.indexes.range.RangeIndex

In [154]:
d={'a':1,'b':2,'c':3} #series using dictionary
li=list(range(3))
s2=pd.Series(d,index=['b','a','c'],name='pb')
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [155]:
type(s2.values)

numpy.ndarray

In [156]:
s2.values


array([2, 1, 3])

In [157]:
s2**3**2

b      512
a        1
c    19683
Name: pb, dtype: int64

In [158]:
a=s2**9
print(a)
b=a**2
print(b)

b      512
a        1
c    19683
Name: pb, dtype: int64
b       262144
a            1
c    387420489
Name: pb, dtype: int64


In [159]:
np.log(s2)

b    0.693147
a    0.000000
c    1.098612
Name: pb, dtype: float64

In [160]:
s2['b':'a']

b    2
a    1
Name: pb, dtype: int64

In [161]:
s2[0:2]

b    2
a    1
Name: pb, dtype: int64

In [162]:
c=pd.Series({'d':22})
s=s2.add(c)
s

a   NaN
b   NaN
c   NaN
d   NaN
dtype: float64

In [163]:
s2

b    2
a    1
c    3
Name: pb, dtype: int64

In [164]:
for i,v in enumerate(s2):
    print(i,"--",v)

0 -- 2
1 -- 1
2 -- 3


In [165]:
li=[x*2 for x in s2]
li

[4, 2, 6]

In [166]:
'c' in s2

True

In [167]:
for k,v in s2.iteritems():
    print(k,v)

b 2
a 1
c 3


In [168]:
li=np.random.rand(5,2,3)
li

array([[[ 0.54977314,  0.18546087,  0.24294436],
        [ 0.6765899 ,  0.88933985,  0.46282813]],

       [[ 0.88831227,  0.66397254,  0.43545406],
        [ 0.51837199,  0.91196563,  0.10211047]],

       [[ 0.10454652,  0.13027759,  0.03413471],
        [ 0.62544886,  0.39317441,  0.38634746]],

       [[ 0.8841175 ,  0.60868246,  0.45266619],
        [ 0.66711754,  0.7840802 ,  0.97283157]],

       [[ 0.46251161,  0.61393123,  0.9041425 ],
        [ 0.83114675,  0.01721317,  0.82882051]]])

In [169]:
li

array([[[ 0.54977314,  0.18546087,  0.24294436],
        [ 0.6765899 ,  0.88933985,  0.46282813]],

       [[ 0.88831227,  0.66397254,  0.43545406],
        [ 0.51837199,  0.91196563,  0.10211047]],

       [[ 0.10454652,  0.13027759,  0.03413471],
        [ 0.62544886,  0.39317441,  0.38634746]],

       [[ 0.8841175 ,  0.60868246,  0.45266619],
        [ 0.66711754,  0.7840802 ,  0.97283157]],

       [[ 0.46251161,  0.61393123,  0.9041425 ],
        [ 0.83114675,  0.01721317,  0.82882051]]])

In [170]:
di={'name':['prince','bharti','rahul','tiwari'],'s.no':[22,45,23,655]}
p=

SyntaxError: invalid syntax (<ipython-input-170-0baf158b1208>, line 2)

In [171]:
data.head()

Name PClass    Age     Sex  \
sno                                                                        
1                     Allen, Miss Elisabeth Walton    1st  29.00  female   
2                      Allison, Miss Helen Loraine    1st   2.00  female   
3              Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
4    Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
5                    Allison, Master Hudson Trevor    1st   0.92    male   

     Survived  SexCode  
sno                     
1           1        1  
2           0        1  
3           0        0  
4           0        1  
5           1        0

## Sorting of dataframe elements

In [71]:
data.head()

Name PClass    Age     Sex  \
sno                                                                        
1                     Allen, Miss Elisabeth Walton    1st  29.00  female   
2                      Allison, Miss Helen Loraine    1st   2.00  female   
3              Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
4    Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
5                    Allison, Master Hudson Trevor    1st   0.92    male   

     Survived  SexCode  
sno                     
1           1        1  
2           0        1  
3           0        0  
4           0        1  
5           1        0

In [73]:
data.sort_index().head(10) # default axis is 0 and sorting wrt to rows

Name PClass    Age     Sex  \
sno                                                                        
1                     Allen, Miss Elisabeth Walton    1st  29.00  female   
2                      Allison, Miss Helen Loraine    1st   2.00  female   
3              Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
4    Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
5                    Allison, Master Hudson Trevor    1st   0.92    male   
6                               Anderson, Mr Harry    1st  47.00    male   
7                 Andrews, Miss Kornelia Theodosia    1st  63.00  female   
8                           Andrews, Mr Thomas, jr    1st  39.00    male   
9     Appleton, Mrs Edward Dale (Charlotte Lamson)    1st  58.00  female   
10                          Artagaveytia, Mr Ramon    1st  71.00    male   

     Survived  SexCode  
sno                     
1           1        1  
2           0        1  
3           0        0  
4           0        1  
5           1        0  
6           1        0  
7           1        1  
8           0        0  
9           1        1  
10          0        0

In [81]:
data.sort_index(axis=1).head(10).head() # axis is 1(coulumn) and sorting w.r.t to columns

Age                                           Name PClass     Sex  \
sno                                                                        
1    29.00                   Allen, Miss Elisabeth Walton    1st  female   
2     2.00                    Allison, Miss Helen Loraine    1st  female   
3    30.00            Allison, Mr Hudson Joshua Creighton    1st    male   
4    25.00  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  female   
5     0.92                  Allison, Master Hudson Trevor    1st    male   

     SexCode  Survived  
sno                     
1          1         1  
2          1         0  
3          0         0  
4          1         0  
5          0         1

#### sorting the contents of columns

##### way1 : using order method , Note: this method returns series.


In [92]:
data.Name.order(ascending=False).head(30)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: order is deprecated, use sort_values(...)
  if __name__ == '__main__':


sno
390     del Carlo, Mrs Sebastiano (Argenia Genovese)
389                         del Carlo, Mr Sebastiano
82                        de Villiers, Madame Berthe
388                        de Brito, Mr Jose Joaquim
1313                                  Zimmerman, Leo
1311                                Zenni, Mr Philip
1310                          Zakarian, Mr Maprieder
1309                              Zakarian, Mr Artun
1308                             Zabour, Miss Tamini
1307                             Zabour, Miss Hileni
598                            Yrois, Miss Henriette
1306                              Youssef, Mr Gerios
289                          Young, Miss Marie Grice
1305                             Yasbeck, Mrs Antoni
1304                              Yasbeck, Mr Antoni
1303                               Yalsevac, Mr Ivan
288                                Wright, Mr George
597                              Wright, Miss Marion
287                                 Woolne

In [93]:
type(data.Name.order(ascending=False).head(30)) ## return type of order is a series 

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: order is deprecated, use sort_values(...)
  if __name__ == '__main__':


pandas.core.series.Series

##### way2 : using sort_index() method to sort the contents of columns , Note: this method returns data frame 

###### case1: sort wrt to 1 column 

In [98]:
d1=data.sort_index(ascending=False, by=['Age'])
d1.head(5)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


Age                                               Name PClass     Sex  \
sno                                                                           
506  71.0                         Mitchell, Mr Henry Michael    2nd    male   
120  71.0                           Goldschmidt, Mr George B    1st    male   
10   71.0                             Artagaveytia, Mr Ramon    1st    male   
73   70.0                     Crosby, Captain Edward Gifford    1st    male   
74   69.0  Crosby, Mrs Edward Gifford (Catherine Elizabet...    1st  female   

     SexCode  Survived  
sno                     
506        0         0  
120        0         0  
10         0         0  
73         0         0  
74         1         1

###### case2: sort wrt to 2 columns 

In [135]:
d2=data.sort_index(ascending=[False,False], by=['Age','Name'])
d2.head(5)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


Age                                               Name PClass     Sex  \
sno                                                                           
506  71.0                         Mitchell, Mr Henry Michael    2nd    male   
120  71.0                           Goldschmidt, Mr George B    1st    male   
10   71.0                             Artagaveytia, Mr Ramon    1st    male   
73   70.0                     Crosby, Captain Edward Gifford    1st    male   
74   69.0  Crosby, Mrs Edward Gifford (Catherine Elizabet...    1st  female   

     SexCode  Survived  
sno                     
506        0         0  
120        0         0  
10         0         0  
73         0         0  
74         1         1

###### case3: sort wrt to 3 columns 

In [136]:
d3=data.sort_index(ascending=[False,True,True], by=['Age','PClass','Name'])
d3.head(5)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  if __name__ == '__main__':


Age                                               Name PClass     Sex  \
sno                                                                           
10   71.0                             Artagaveytia, Mr Ramon    1st    male   
120  71.0                           Goldschmidt, Mr George B    1st    male   
506  71.0                         Mitchell, Mr Henry Michael    2nd    male   
73   70.0                     Crosby, Captain Edward Gifford    1st    male   
74   69.0  Crosby, Mrs Edward Gifford (Catherine Elizabet...    1st  female   

     SexCode  Survived  
sno                     
10         0         0  
120        0         0  
506        0         0  
73         0         0  
74         1         1